URL = "https://1000kitap.com/akis"
PROFILE = "Profil"
LOGIN = "//*[@id='__next']/div/div/div[4]/div/div[2]/a/span"
EMAIL = "//input[@value=\'\']"
EMAIL_ADDRESS = "temoc46551@carspure.com"
PASSWORD_FIELD = "//div[2]/div/input"
PASSWORD = "123789"
LOGIN_BUTTON = "//*[@id='__next']/div/div/div[4]/div/div[2]/div/div[3]/button[2]/span"
ORGANIZE = ":r40:"
ORGANIZE_PROFILE = ".min-h-11:nth-child(1) .text"
AVATAR = "//*[@id='__next']/div/div/div[4]/div/div[1]/div[2]/div[2]/div[2]/button/div"